### ISSUE TITLE
Version 2 of the API

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/JHelioviewer#100]
We have been developing a new version of the API which will support more complex data types in the future.    The new API is intended to offer greater flexibility.  The new API was introduced in the meeting we had earlier this year (2014).  As was mentioned in the meeting, we anticipate supporting version 1 of the API until the end of 2015.  After that, version 2 will be the only one available.  Details of the API can be found at http://api.helioviewer.org/docs/v2/.

**Comment by deiruch** [comment]
Implemented in new architecture.
