### ISSUE TITLE
Add checkbox to launch JHV automatically after installer completes

### ISSUE THREAD

**Issue by deiruch** [Helioviewer-Project/JHelioviewer#115]
The last screen of the install wizard should have a (by default enabled) checkbox that launches JHV after installation.

**Comment by deiruch** [comment]
This checkbox should be also there for updates. It's currently only appearing in regular installations.

**Comment by StefanMeier13** [comment]
It's done, the current version is a build without this button. In the next release it work. The version Beta-10 haven't this implemented
