### ISSUE TITLE
Fatal Error! The Kakadu libraries could not be loaded

### ISSUE THREAD

**Issue by DaveLangstaff** [Helioviewer-Project/JHelioviewer#123]
I have a problem with a number of installations of jHelioviewer that have all started giving the following error message on jHelioviewer startup:
"Error Loading Kakadu libraries. Fatal Error The Kakadu libraries could not be loaded. The log file may contain further information"

These are machines running windows 7 or Windows 8. The Windows 7 machines were running jHelioviewer successfully a year ago, however they have all stopped working, possibly due to a Java update. I have tried disabling Windows firewall, but it made no difference.

Any ideas as to why this may be happening and how I could fix it?

**Comment by StefanMeier13** [comment]
It should be fixed now. We recommend to use the new JHelioviewer-Version, https://github.com/Helioviewer-Project/JHelioviewer/releases/tag/v2.3-beta.12.
This version is more faster and stable.

**Comment by DaveLangstaff** [comment]
Hi Stefan,

Many thanks for looking into that.

Strangely enough, the existing version also started working this afternoon – did you do something to the libraries ?

Also, is there 1 32-bit windows version of jHelioviewer or is only the 64 bit version supported nowdays?

Thanks again for your help
Regards

**Comment by StefanMeier13** [comment]
Hey,
We changed the server of the webpage. The old version of JHelioviewer download the libraries from the server. The new one include all the libraries in the release. Also the JVM should be included.
Yes for windows, we support just 64 bit.
No Problem
Regards
