### ISSUE TITLE
Jar and jnlp 

### ISSUE THREAD

**Issue by PabloIAS** [Helioviewer-Project/JHelioviewer#180]
Hello, 
Would it be possible to have a *.jar and a *.jnlp example file ?
Some users would like to call Jhelioviewer from a webapp 

Regards, 
Pablo 
IAS

**Comment by deiruch** [comment]
Hi Pablo

Thanks for the suggestion! After internal discussions we decided not to support JNLP and/or deployment as Web Start application. The technology is not supported by OpenJDK and therefore won't work on neither OS X nor Linux. As you can see on http://www.oracle.com/technetwork/java/eol-135779.html Oracle itself will stop supporting Web Start in 2017. 

We feel that our new deployment model with automatic updates should serve most users better. If you feel different about this, it should be easy to create a signed JAR directly from the repository and deploy it yourself.

Cheers,
Simon
