### ISSUE TITLE
Save view mode of the user

### ISSUE THREAD

**Issue by MedocIAS** [Helioviewer-Project/JHelioviewer#185]
Hello, 
Is there a way to start 2.3 version in 2D mode ?
Is there an option we can add at the command line to do so ?

Medoc Team 
IAS

**Comment by deiruch** [comment]
The next version will restore the camera mode to the previous state on startup. Thanks for the great idea!

**Comment by MedocIAS** [comment]
Hello, 
Yes it will be great. 
What about the size of the display view , the left panel layout (collapse or not )?
Would it be possible to save that as well ? 
see image joined 
![save_config_jhv](https://cloud.githubusercontent.com/assets/3584929/7367405/85d18104-ed9f-11e4-878d-4327462be9af.jpg)

**Comment by deiruch** [comment]
Please don't post new issues as comments to existing issues. I created a new issue #187 for this request.
