### ISSUE TITLE
Location of user settings 

### ISSUE THREAD

**Issue by MedocIAS** [Helioviewer-Project/JHelioviewer#186]
Hello, 
Where are stored the setting configured by the users in the 2.3 beta.

NB:
In the 2.2 a /home/#user/JHelioviewer directory was created and we could find subdirectories : 
Cache  Colortables  Downloads  Exports  Libs  Logs  Plugins  Settings  States  Temp  VSOData

Medoc Team

**Comment by deiruch** [comment]
1. Default settings are stored in the application path
2. User settings are stored in a platform-specific location (using Java's prefs system)

In general: Please direct future questions at support@jhelioviewer.org and don't post in the issue tracker. We hope to use the issue tracker for bugs, not as support forum. We'll happily provide support via e-Mail, Skype, or other communication channels. No offence meant!

Cheers,
Simon

**Comment by MedocIAS** [comment]
Thanks 
All right, no problem.
We will use  support@jhelioviewer.org for questions 

Cheers
