### ISSUE TITLE
Wait for adding layer dialog

### ISSUE THREAD

**Issue by StefanMeier13** [Helioviewer-Project/JHelioviewer#233]

**Comment by deiruch** [comment]
Maybe it's smarter to use a warning sign to the layer manager instead /!\

1. Layers should be added immediately
2. Download problems of any sort (first frame, subsequent JPIP requests, ...) lead to a warning/error icon in the layer manager, near this layer
3. Clicking the warning/error icon shows a dialog, describing the encountered problems ("Images could not be downloaded. Server replied with HTTP code 404. This happened with 23497 other requests as well.") and possible actions ("Retry failed downloads", "Remove layer", "Ignore")
