### ISSUE TITLE
Black line at limb when zooming in

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/JHelioviewer#242]
See attached.

JHV 2.3.3 / Mac OS 10.10.4 / MacBook Air early 2014 
Line appears as little black dots when zoomed out.

![jhv new](https://cloud.githubusercontent.com/assets/983575/9262595/2e9832b8-41e4-11e5-88c8-e5ac3db7c12c.png)

**Comment by StefanMeier13** [comment]
This would be solved with the version 3.0
