### ISSUE TITLE
32-bit version of JHelioviewer

### ISSUE THREAD

**Issue by kosmodrey** [Helioviewer-Project/JHelioviewer#273]
Hello,
I simply can't install JHelioviewer on my 32-bit Windows 10 machine. Is there any plans to complicate and distribute binaries for 32-bit systems?

**Comment by deiruch** [comment]
Hi Kosmodrey

No, there are currently no plans to distribute a 32bit version. JHelioviewer requires a lot of memory to cache image data, metadata and other things - which often leads to errors and problems within minutes of using it.

If you still want to use it on an older 32bit machine, you can always install and use the older 2.2 releases.

Kind regards,
Simon
