### ISSUE TITLE
Internal Server Error on startup

### ISSUE THREAD

**Issue by live4right** [Helioviewer-Project/JHelioviewer#276]
Hello,
I downloaded the JHelioviewer to my computer and ran the install. I started up but for some reason it continually returns a internal server error 500. What is the new server to connect to? Apparently the helioviewer.ias-psud.fr server is having issues and a new one is needed. Any help would be appreciated as the ui of the JHelioviewer  has many more options than the web based version. Thanks

--Carl

**Comment by deiruch** [comment]
Hi Carl

Thanks for the report! This issue is being tracked here:
https://github.com/Helioviewer-Project/api/issues/7

Cheers
