### ISSUE TITLE
After video export visualization is "freaking out"

### ISSUE THREAD

**Issue by ennosigaeus** [Helioviewer-Project/JHelioviewer#288]
I created a new layer (SDO, AIA 171, 5min cadence, 12-01-2015 00:00 - 13-01-2015 23:23:59) and started downloading data. After I felt the quality was OK, I selected a view (using the zoom box button) and exported a video. The export worked well, but now the visualization seems to be stuck in some very short loop when paused (skipping back and forth between 2 frames). Upon clicking on the play button, the visualization starts skipping back and forth even faster. The only way to stop it is to restart JHelioviewer (just removing that layer does not help).

**Comment by Hackempluf** [comment]
Fixed in Pre-release 3.0.19
