### ISSUE TITLE
Many of the Images Are Darker and Darker in Comparison with Previous Releases and with the SDO Page

### ISSUE THREAD

**Issue by live4right** [Helioviewer-Project/JHelioviewer#290]
Hi,
 I really enjoy using the jhelioviewer for monitoring the sun. I have actually determined there is a connection between the solar flares and severe weather events... Anyway I noticed that with each progressive release the images are becoming darker and darker. While on the SDO website they are as bright as ever. I have tried working with the various gamma settings and such but to no avail. What has happened to the coloring? I will include 2 screen shots same settings with jhelioviewer just 6 years apart. Maybe you can shed some light on this as I would like the coloring of 2010 back in the current version

Thanks,
Carl

![sdo 304 2010 image](https://cloud.githubusercontent.com/assets/13044191/17267257/35fb9f2c-55ca-11e6-975e-64c0736c7ecd.png)

![sdo 304 2016 image](https://cloud.githubusercontent.com/assets/13044191/17267256/35c80856-55ca-11e6-928a-ccdb66bf7ae1.png)

**Comment by deiruch** [comment]
This issue was moved to Helioviewer-Project/helioviewer.org#136
