### ISSUE TITLE
ArrayIndexOutOfBoundsException in LayerPanel.java:585

### ISSUE THREAD

**Issue by deiruch** [Helioviewer-Project/JHelioviewer#297]
org.helioviewer.jhv.gui.LayerPanel$ImageIconCellRenderer.getTableCellRendererComponent in LayerPanel.java:585
javax.swing.JTable.prepareRenderer:-1
javax.swing.plaf.basic.BasicTableUI.paintCell:-1
javax.swing.plaf.basic.BasicTableUI.paintCells:-1
javax.swing.plaf.basic.BasicTableUI.paint:-1
javax.swing.plaf.ComponentUI.update:-1
javax.swing.JComponent.paintComponent:-1
javax.swing.JComponent.paint:-1
javax.swing.JComponent.paintToOffscreen:-1
javax.swing.RepaintManager$PaintManager.paintDoubleBuffered:-1
javax.swing.RepaintManager$PaintManager.paint:-1
javax.swing.RepaintManager.paint:-1
javax.swing.JComponent._paintImmediately:-1
javax.swing.JComponent.paintImmediately:-1
javax.swing.RepaintManager$4.run:-1
javax.swing.RepaintManager$4.run:-1
java.security.AccessController.doPrivileged:-2
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege:-1
javax.swing.RepaintManager.paintDirtyRegions:-1
javax.swing.RepaintManager.paintDirtyRegions:-1
javax.swing.RepaintManager.prePaintDirtyRegions:-1
javax.swing.RepaintManager.access$1200:-1
javax.swing.RepaintManager$ProcessingRunnable.run:-1
java.awt.event.InvocationEvent.dispatch:-1
java.awt.EventQueue.dispatchEventImpl:-1
java.awt.EventQueue.access$500:-1
java.awt.EventQueue$3.run:-1
java.awt.EventQueue$3.run:-1
java.security.AccessController.doPrivileged:-2
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege:-1
java.awt.EventQueue.dispatchEvent:-1
java.awt.EventDispatchThread.pumpOneEventForFilters:-1
java.awt.EventDispatchThread.pumpEventsForFilter:-1
java.awt.EventDispatchThread.pumpEventsForHierarchy:-1
java.awt.EventDispatchThread.pumpEvents:-1
java.awt.EventDispatchThread.pumpEvents:-1
java.awt.EventDispatchThread.run:-1

Version: 3.0.12

**Comment by Hackempluf** [comment]
This should be fixed in Pre-Release 3.0.19
