### ISSUE TITLE
Jhelioviewer within eclipse 

### ISSUE THREAD

**Issue by PabloA-dev-coder** [Helioviewer-Project/JHelioviewer#301]
I would like to start JHelioviewer within eclipse

I did a git clone from the git repository doing

git clone https://github.com/Helioviewer-Project/JHelioviewer-SWHV.git

but I have a "No projects are found to import" in eclipse when I try to import an existing project

according to http://wiki.helioviewer.org/wiki/JHelioviewer_Development_Information#Configuring_Eclipse

Do you have clue  ?

**Comment by deiruch** [comment]
Please post questions regarding SWHV here:
https://github.com/Helioviewer-Project/JHelioviewer-SWHV/issues
