### ISSUE TITLE
JHelioviewer: can't access any images

### ISSUE THREAD

**Issue by pryoung** [Helioviewer-Project/JHelioviewer#306]
I ran JHelioviewer for the first time in a while last week, and it couldn't find any images. I tried again today and it still can't access any images. Please can you fix this. I'm using version 2.3.3 on a Mac.

The message I get when starting up JHelioviewer is attached.

<img width="943" alt="screen shot 2019-01-14 at 6 06 27 pm" src="https://user-images.githubusercontent.com/18336264/51147146-24b2ce80-1827-11e9-83e2-3366cdbd2ac8.png">

**Comment by deiruch** [comment]
Version 2.3.3 is outdated. Please download a more recent version from http://www.jhelioviewer.org/
